# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMusicPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SDWebImage'
	pod 'Alamofire'
	pod 'MJRefresh' 
	pod 'SwiftLint'
	pod 'SwiftLint'
	pod 'SwiftyJSON'
  # Pods for MyMusicPlayer

  target 'MyMusicPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMusicPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
